language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -U setuptools
- python setup.py install
script:
- python -m unittest
deploy:
  provider: pypi
  user: "$PYPI_USERNAME"
  password: "$PYPI_PASSWORD"
  on:
    tags: true
    python: '3.6'
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true